### ISSUE TITLE
Item Types

### ISSUE THREAD

**Issue by MarkHammond34** [sim0nx/python-openhab#1]
Hi there. Just wondering what item types that are defined in this library. I noticed you have a general Item object and a SwitchItem too. I would like to set the state of a dimmer light to 50 but 'light.state = '50'' does not work for me. Thanks!

**Comment by sim0nx** [comment]
Hey, Sorry for not getting back to you earlier, I totally forgot about this issue :-(

Anyways, I have just pushed an update which does include support for dimmer items. the switch item it not suited for this as it only accepts on/off (as per the specs).
