### ISSUE TITLE
Reference information to this repository

### ISSUE THREAD

**Issue by cedrikschueler** [sim0nx/python-openhab#10]
As our project group at university is coming to an end we are currently writing some documentation.

As your project was a nice tool for us to request the openHAB Rest-API in a safe way we would like to put a reference to you in our documentation (even if it might not be published anywhere).

Is this bib-entry okay?

``` latex
@misc{python-openhab,
    author = "Georges Toth",
    title = "Python-openHAB: python library for accessing the openHAB REST API",
    url = "github.com/sim0nx/python-openhab"
}
```

Thanks for your project and feedback!

**Comment by sim0nx** [comment]
Absolutely thank you, appreciate it :-)
In case it gets published feel free to share the link!
