### ISSUE TITLE
Setting items state to NULL and UNDEF

### ISSUE THREAD

**Issue by rb1205** [sim0nx/python-openhab#12]
Is there a way to set an item state to NULL or UNDEF? I tried python's None and strings "NULL",  "UNDEF" and "", but they all raise an Invalid Value exception.

**Comment by sim0nx** [comment]
This is not allowed by the this library. According to the documentation items are created with the value NULL and a binding may set its value to UNDEF if it looses communication etc.

I am not sure this would even work (haven't tested it either). Why would you need this?

If you can verify manually that it works I could add it.

**Comment by rb1205** [comment]
The latter: I wrote a client in python that polls my heatpump for data, and then I use your binding to send the data to openhab.

This works great (thanks for your work BTW), however when the heatpump is off or the interface is disconnected and the polling fails I want the data to become UNDEF to block rules from working with stale data. At the moment I work around this by using expire in openhab, but being able to set UNDEF directly from your binding would be much better.

**Comment by sim0nx** [comment]
I have implemented your request in the master branch.
Could you please install the library directly from github and verify if this works as expected for you ?
(```pip install -U https://github.com/sim0nx/python-openhab```)

You can use the following methods on your items:
- item.update_state_null()
- item.update_state_undef()

**Comment by rb1205** [comment]
Works great!! Thank you man!

While testing it I noticed that both NULL and UNDEF states are translated as None when queried. I'll make a PR to fix that.

**Comment by rb1205** [comment]
Ooops, with this release I get a "not iterable" exception when I try to update the state of an item to an integer or float:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/openhab/items.py", line 76, in state
    self.update(value)
  File "/usr/local/lib/python3.7/dist-packages/openhab/items.py", line 140, in update
    self._update(value)
  File "/usr/local/lib/python3.7/dist-packages/openhab/items.py", line 127, in _update
    self.openhab.req_put('/items/{}/state'.format(self.name), data=value)
  File "/usr/local/lib/python3.7/dist-packages/openhab/client.py", line 134, in req_put
    r = self.session.put(self.base_url + uri_path, data=data, timeout=self.timeout)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 593, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 469, in send
    for i in request.body:
TypeError: 'float' object is not iterable
```
looks like it misses an str(value) somewhere in items.py.

**Comment by sim0nx** [comment]
I have added two methods for checking if the actual state is UNDEF or NULL. I do need to keep the ".state" as None in both cases but this allows for checking what exactly it is, in case of None...

Could you please try this out?

**Comment by sim0nx** [comment]
> Ooops, with this release I get a "not iterable" exception when I try to update the state of an item to an integer or float:
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.7/dist-packages/openhab/items.py", line 76, in state
>     self.update(value)
>   File "/usr/local/lib/python3.7/dist-packages/openhab/items.py", line 140, in update
>     self._update(value)
>   File "/usr/local/lib/python3.7/dist-packages/openhab/items.py", line 127, in _update
>     self.openhab.req_put('/items/{}/state'.format(self.name), data=value)
>   File "/usr/local/lib/python3.7/dist-packages/openhab/client.py", line 134, in req_put
>     r = self.session.put(self.base_url + uri_path, data=data, timeout=self.timeout)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 593, in put
>     return self.request('PUT', url, data=data, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 469, in send
>     for i in request.body:
> TypeError: 'float' object is not iterable
> ```
> 
> looks like it misses an str(value) somewhere in items.py.

Could you please share some code snippets so I can debug this on my side?

**Comment by rb1205** [comment]
"PdC1_Valve" is a Number type item in openhab

```
from openhab import OpenHAB
oh2=OpenHAB('http://localhost:8080/rest')
it=oh2.get_item('PdC1_Valve')
it.state=1.0
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/openhab/items.py", line 76, in state
    self.update(value)
  File "/usr/local/lib/python3.7/dist-packages/openhab/items.py", line 140, in update
    self._update(value)
  File "/usr/local/lib/python3.7/dist-packages/openhab/items.py", line 127, in _update
    self.openhab.req_put('/items/{}/state'.format(self.name), data=value)
  File "/usr/local/lib/python3.7/dist-packages/openhab/client.py", line 134, in req_put
    r = self.session.put(self.base_url + uri_path, data=data, timeout=self.timeout)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 593, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 469, in send
    for i in request.body:
TypeError: 'float' object is not iterable

```

**Comment by sim0nx** [comment]
Oops small typo... fixed it, can you retest please ?

**Comment by rb1205** [comment]
Yep, seems to work just fine now. I see you also added is_state_null / is_state_undef methods yourself, good one!

Closing the issue.

**Comment by sim0nx** [comment]
Thanks for testing, I'll publish a new version on pypi then.
