### ISSUE TITLE
AttributeError: 'Session' object has no attribute 'requests

### ISSUE THREAD

**Issue by mappjo** [sim0nx/python-openhab#13]
Hi there
i try to make the program safe even with connection problems.
 if  iptest():
        print(WertI)
        try:
            Item.state = WertI
        except openhab.session.requests.exceptions.HTTPError as errh:
            print (DT + "Http Error:",errh)
            ErrorLog = open (DT + 'ErrorLog.txt', 'a')
            ErrorLog.write (DT + "Http Error: %d \n" % errh)
            ErrorLog.close()
            return
        except openhab.session.requests.exceptions.ConnectionError as errc:
                print (DT + "Error Connecting:",errc)
                ErrorLog = open (DT + 'ErrorLog.txt', 'a')
                ErrorLog.write (DT + "Error Connecting: %d \n" % errc)
                ErrorLog.close()
                return
        except openhab.session.requests.exceptions.Timeout as errt:
            print (DT + "Timeout Error:",errt)
            ErrorLog = open (DT + 'ErrorLog.txt', 'a')
            ErrorLog.write (DT + "Timeout Error:%d \n" % errt)
            ErrorLog.close()
            return
        except:
            print (DT + "any Error:")
            ErrorLog = open (DT + 'ErrorLog.txt', 'a')
            ErrorLog.write (DT + "any Error" + "\n")
            ErrorLog.close()
            return   
    else:
        Untbr = Untbr +1

The Problem is 
except openhab.session.requests.exceptions.HTTPError as errh:
AttributeError: 'Session' object has no attribute 'requests'

Tanks and a "Happy new Year "

**Comment by sim0nx** [comment]
Hi,

What you need is to catch exceptions from the requests library for everything connection related.
See here: https://2.python-requests.org/en/master/user/quickstart/#errors-and-exceptions    and    https://2.python-requests.org/en/master/_modules/requests/exceptions/

Thanks, "Happy new year" to you too
