### ISSUE TITLE
error updating items with non-latin strings

### ISSUE THREAD

**Issue by izharm** [sim0nx/python-openhab#17]
Hi,
I am trying to update a string item with non-latin characters.
when I do:
`routetowork.state = 'שלום'`

the PUT fails :
```
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1289, in _send_request
    body = _encode(body, 'body')
  File "/usr/lib/python3.7/http/client.py", line 170, in _encode
    (name.title(), data[err.start:err.end], name)) from None
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-3: Body ('שלום') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```

UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-3
when I do:

`routetowork.state = 'שלום'.encode('utf-8')`

I get
```
File "/usr/local/lib/python3.7/dist-packages/openhab/items.py", line 109, in _validate_value
    raise ValueError()
```
if I leave the .encode('utf-8') and comment line 163: 
`#self._validate_value(value)`
everything works.

Thanks,

**Comment by sim0nx** [comment]
Hi,

I have fixed this issue in the latest release. Please update to 2.13.3.
If you still encounter problems, please reopen this issue.
