### ISSUE TITLE
Openhab 3.0 OAuth2 authentification

### ISSUE THREAD

**Issue by TheNetStriker** [sim0nx/python-openhab#23]
With the new OpenHab 3.0 release the rest service is now using OAuth2 to authenticate users. Is this already possible with this library or will this feature be added in the future?

**Comment by sim0nx** [comment]
You may use basic authentication with OH3 after enabling it in the UI though I agree this should be added.

It is not supported yet but definitely on the todo. I did some quick tests to see how this works with OH3 and can be done. I will update this issue once it's done.

**Comment by ramack** [comment]
This sounds like a helpful improvement. Is there an update on this expected anytime soon?
- I don't want to put pressure, but I also know that it is much more fun to implement features that are interesting for others, so I want to let you know that it would be great to have...

**Comment by sim0nx** [comment]
Thanks @ramack :-)

I have made changes which allow for using and testing OAuth2 support. Please see the bottom of the readme file for instructions.

I am not sure yet if I will fully integrate OAuth2 support or if I will let the user manage that part, as shown in the readme. So consider this experimental support.

Could you give this a test ?

**Comment by sim0nx** [comment]
I have just made a new release with integrated OAuth2 support. Please see the readme and/or documentation on how to use it.
