### ISSUE TITLE
Expose _unitOfMeasure

### ISSUE THREAD

**Issue by kubawolanin** [sim0nx/python-openhab#26]
Hi! Currently in the code I see just one reference to `_unitOfMeasure`:

```
    if self.is_undefined(self._raw_state):
      self._state = None
    else:
      self._state, self._unitOfMeasure = self._parse_rest(self._raw_state)
```

The property is not initiated and it's not accessible from the API.

Would be great to get it separately.

Best regards and thank you for your hard work!

**Comment by sim0nx** [comment]
Hi thanks! ... I fixed the implementation and exposed the value returned by the API.

```python
item.unit_of_measure
```
