### ISSUE TITLE
The 'pip==20.3.4' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by Dennux** [sim0nx/python-openhab#29]
i get the following error:

clean install of python3.11

 File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 868, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pip._vendor.pkg_resources.DistributionNotFound: The 'pip==20.3.4' distribution was not found and is required by the application

**Comment by sim0nx** [comment]
That looks like a broken python install and certainly has nothing to do with this project.
