### ISSUE TITLE
Support persistent method

### ISSUE THREAD

**Issue by Krata4** [sim0nx/python-openhab#30]
Hello,

thank you for this librarzy. I am using this for writing logic in Python.
It would help me to use persisten REST service. Are you planning to support get date for the item based on persistent REST?

Thanks
Jirka

**Comment by sim0nx** [comment]
Hi,
Glad to hear that and thanks for your PR :-)

I took a bit of a different approach allowing for all params the REST API supports in regards to that endpoint.

You can achieve what you need using something like:
```python
item = openhab.get_item('test')

start_time = datetime.datetime.fromtimestamp(1695504300123 / 1000, tz=datetime.UTC)
end_time = datetime.datetime.fromtimestamp((1695504300123 / 1000) + 1, tz=datetime.UTC)

persistence_data = list(item.persistence(start_time=start_time, end_time=end_time))
print(persistence_data[0])
```

-> *get_item_persistence()* / *persistence()* return an iterator

Hope this helps

**Comment by Krata4** [comment]
Thanks, it looks good :-)
