### ISSUE TITLE
model_dump error: pydantic 2.0 vs pydantic 1.10

### ISSUE THREAD

**Issue by bob-tm** [sim0nx/python-openhab#33]
Hello, 

Latest openhab code requires pydantic 2.0

` token=self.oauth2_config.token.model_dump(),`

model_dump is absent in pydantic 1.10 

it it possible to adapt openhab code to pydantic 1.10 ?
I try to add pydantic 2.0 to manifest.json, but always receive

Cannot install pydantic==2.* because these package versions have conflicting dependencies.

have no ideas ...

**Comment by sim0nx** [comment]
Hi,

What python version are you using ?
Where does that *manifest.json* come from ?
