### ISSUE TITLE
Number:Temperature items are not updated

### ISSUE THREAD

**Issue by JungeG** [sim0nx/python-openhab#4]
My item in openHAB:
`Number:Temperature BoilerTemperature "BoilerTemperatur [%.1f °C]"`

My python coding: 

````
#!/usr/bin/python3
# -*- coding: utf-8 -*-
from openhab import openHAB

#openHAB Verbindung 
base_url = 'http://192.168.XXX.XX:8080/rest'
openhab = openHAB(base_url)

...

BoilerTemperature = openhab.get_item('BoilerTemperature')
...
BoilerTemperature.command("58.5")`

````
When running this code I get following error message (on a MAC):

> Traceback (most recent call last):
>   File "/Users/georg/Documents/python/test2.py", line 24, in <module>
>     BoilerTemperature.command("58.5")
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/openhab/items.py", line 141, in command
>     self._validate_value(value)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/openhab/items.py", line 99, in _validate_value
>     raise ValueError()
> ValueError

It seems to be a validation error in the "openHAB" coding. If I change to a "straight" Number item the update works without any problem.
Thanks for support
Georg

**Comment by sim0nx** [comment]
Hmm I don't have such items, could you please post the output of:
```
curl -X GET --header "Accept: application/json" "http://192.168.XXX.XX:8080/rest/items/BoilerTemperature"
```

?

**Comment by JungeG** [comment]
Here the output:

**{"link":"http://192.168.185.49:8080/rest/items/BoilerTemperature","state":"49.0 °C","stateDescription":{"pattern":"%.1f °C","readOnly":false,"options":[]},"editable":false,"type":"Number:Temperature","name":"BoilerTemperature","label":"BoilerTemperatur","tags":[],"groupNames":[]}**

If I call the BoilerTemperature within Python it looks like:
**<Number:Temperature - BoilerTemperature : 49.0>**

Does this help?
Thanks Georg

**Comment by sim0nx** [comment]
Took a bit longer but I fixed it in master. Will publish a new version of this library soon! :-)
