### ISSUE TITLE
Rollershutter type not supported

### ISSUE THREAD

**Issue by cedrikschueler** [sim0nx/python-openhab#7]
python-openhab does not involve the rollershutter type.
As a workaround there are two ways:

1. Changing the items to Dimmer in openHAB
<details><p><summary>foo.items (click for expansion)</summary>

``` java 
// e.g. from this:
Rollershutter   Shutter      "Jalousie"                  <rollershutter>   (LivingRoom, gShutter)   ["Rollershutter"]                  {channel=""}
// to this
Dimmer   Shutter      "Jalousie"                  <rollershutter>   (LivingRoom, gShutter)   ["Rollershutter"]                  {channel=""}
```

</p></details>

2. Assigning the rollershutter to a `DimmerItem` in python-openhab
<details><p><summary>client.py (click for expansion)</summary>

``` python 
  # in line 199
  elif json_data['type'] in ['Dimmer', 'Rollershutter']:
    return openhab.items.DimmerItem(self, json_data)
```

</p></details>
Maybe a RollershutterItem should be defined?

**Comment by sim0nx** [comment]
Sorry for not getting back earlier to you on this.... could you please test the latest master version and let me know if this works for you ?

```
pip install -U git+https://github.com/sim0nx/python-openhab.git
```

**Comment by cedrikschueler** [comment]
Works!
