### ISSUE TITLE
Contact Item not valid

### ISSUE THREAD

**Issue by cedrikschueler** [sim0nx/python-openhab#9]
I just found out the following bug:

If you try to set the state of a contact item it fails with an value error
``` python
    raise ValueError('Invalid value "{}"'.format(value))
ValueError: Invalid value "CLOSED"

```

If you take a look on the documentation this makes sense as the contact item is a "read only" item ([click for documentation](https://www.openhab.org/docs/configuration/items.html#type)).

Anyways there are still [functions implemented](https://github.com/sim0nx/python-openhab/blob/master/openhab/items.py#L227) to set the state.
This might affect other item types too!

**Comment by sim0nx** [comment]
Thanks for reporting.

According to the documentation the item of type contact is not read-only, but it only accepts updates, not commands.
I have fixed this to raise an exception if you try to send a command to such an item.

Updates should be done via the helper methods *.open()* / *.close()*. Sending an update with *.update('OPEN')* / *.update('CLOSED')* is also fine though and works as expected.

I have checked and only contact items seem to act this way (at least for the types currently implemented).
